name: Concurrency 1
run-name: Concurrency 1 (${{ inputs.enviroment }})
on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: "Environment"
        type: environment
        required: true

concurrency:
  group: ${{ github.event.inputs.enviroment }}
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30